import { Inter } from "next/font/google";
import "./globals.css";
import { ReminderProvider } from '../../my-app/context/ReminderContext'; // Adjust the path if needed
import { AuthProvider } from "./Providers";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-pt">
      <body className={inter.className}>
        <AuthProvider>
          <ReminderProvider>
            {children}
          </ReminderProvider>
        </AuthProvider>
      </body>
    </html>
  );
}